### ISSUE TITLE
Website needs new images

### ISSUE THREAD

**Issue by shaunagm** [princeton-1/princeton-1.github.io#7]
I'm pretty sure that's the wrong kind of Princeton.

We need someone to replace the images with something else. It is up to you what the new images will be!

A tip:

Make sure that the licensing on the image gives you permission to add them. An easy way to make sure if that is to choose Creative Commons-licensed images. You can find great re-usable images on Wikimedia Commons, at http://flickr.com/creativecommons, or by using the advanced search within Google Image Search, just to name a few options.

**Comment by vlad17** [comment]
I'll get this one.

**Comment by brainwane** [comment]
Vlad fixed this in pull request #10
